version: "3.9"
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: root
    volumes:
      - ./frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    user: frappe
    build:
      context: frappe
      args:
        FRAPPE_URL: https://github.com/frappe/frappe
        FRAPPE_BRANCH: rebrand-ui
        REDIS_CACHE_URL: redis-cache:6379
        REDIS_QUEUE_URL: redis-queue:6379
        REDIS_SOCKETIO_URL: redis-socketio:6379
    # volumes:
    #   - ./development:/workspace/development
    #   - ./development:/workspace/development_mnt
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"
    depends_on:
      - mariadb

volumes:
  mariadb-vol:
